'use strict';

const fs = require('fs');
const path = require('path');
const { EventEmitter } = require('events');

const hasNativeRecursive = require('./has-native-recursive');
const is = require('./is');

// Event type constants
const EVENT_UPDATE = 'update';
const EVENT_REMOVE = 'remove';

// Symbol for skip flag in filter function
const SKIP_FLAG = Symbol('skip');

/**
 * Check if array contains duplicates
 * @param {Array} arr
 * @returns {boolean}
 */
function hasDup(arr) {
  return arr.some((v, i, self) => self.indexOf(v) !== i);
}

/**
 * Remove duplicates from array
 * @param {Array} arr
 * @returns {Array}
 */
function unique(arr) {
  return arr.filter((v, i, self) => self.indexOf(v) === i);
}

/**
 * Validate encoding option
 * @param {string} encoding
 * @throws {Error} If encoding is unknown
 */
function assertEncoding(encoding) {
  if (encoding && encoding !== 'buffer' && !Buffer.isEncoding(encoding)) {
    throw new Error(`Unknown encoding: ${encoding}`);
  }
}

/**
 * Create a filter guard function from filter option
 * @param {Function|RegExp} fn - Filter function or RegExp
 * @returns {Function} Guard function that calls action if filter passes
 */
function guard(fn) {
  if (is.func(fn)) {
    return (arg, action) => {
      if (fn(arg, false)) action();
    };
  }
  if (is.regExp(fn)) {
    return (arg, action) => {
      if (fn.test(arg)) action();
    };
  }
  return (arg, action) => action();
}

/**
 * Convert file names to event messages
 * @param {string[]} names - File names
 * @returns {Array<[string, string]>} Array of [eventType, fileName] tuples
 */
function composeMessage(names) {
  return names.map((n) => (is.exists(n) ? [EVENT_UPDATE, n] : [EVENT_REMOVE, n]));
}

/**
 * Process cached file names and generate event messages
 * Filters out temporary editor files when saving
 * @param {string[]} cache - Cached file names
 * @returns {Array<[string, string]>} Array of [eventType, fileName] tuples
 */
function getMessages(cache) {
  let filtered = unique(cache);

  // Saving file from an editor? If so, assuming the
  // non-existed files in the cache are temporary files
  // generated by an editor and thus be filtered.
  const reg = /~$|^\.#|^##$/g;
  const hasSpecialChar = cache.some((c) => reg.test(c));

  if (hasSpecialChar) {
    const dup = hasDup(cache.map((c) => c.replace(reg, '')));
    if (dup) {
      filtered = filtered.filter((m) => is.exists(m));
    }
  }

  return composeMessage(filtered);
}

/**
 * Create a debounced event handler
 * @param {Object} info - Watch info object
 * @param {Function} fn - Callback function
 * @returns {Function} Debounced handler
 */
function debounce(info, fn) {
  let timer = null;
  let cache = [];
  const { encoding } = info.options;
  const delay = is.number(info.options.delay) ? info.options.delay : 200;

  function handle() {
    getMessages(cache).forEach((msg) => {
      msg[1] = Buffer.from(msg[1]);
      if (encoding !== 'buffer') {
        msg[1] = msg[1].toString(encoding);
      }
      fn(...msg);
    });
    timer = null;
    cache = [];
  }

  return (rawEvt, name) => {
    cache.push(name);
    if (!timer) {
      timer = setTimeout(handle, delay);
    }
  };
}

/**
 * Create a duplicate event filter for composed watchers
 * @returns {Function} Filter function
 */
function createDupsFilter() {
  let memo = {};
  return (fn) => (evt, name) => {
    memo[evt + name] = [evt, name];
    setTimeout(() => {
      Object.keys(memo).forEach((n) => {
        fn(...memo[n]);
      });
      memo = {};
    });
  };
}

/**
 * Safely start watching a path
 * @param {Watcher} watcher - Watcher instance
 * @param {string} dir - Directory to watch
 * @param {Object} opts - Watch options
 * @returns {fs.FSWatcher|undefined}
 */
function tryWatch(watcher, dir, opts) {
  try {
    return fs.watch(dir, opts);
  } catch (e) {
    process.nextTick(() => watcher.emit('error', e));
  }
}

/**
 * Get subdirectories of a directory
 * @param {string} dir - Directory path
 * @param {Function} fn - Callback for each subdirectory
 * @param {Function} [done] - Callback when complete
 */
function getSubDirectories(dir, fn, done = () => {}) {
  if (is.directory(dir)) {
    fs.readdir(dir, (err, all) => {
      if (err) {
        // Don't throw permission errors
        if (/^(EPERM|EACCES)$/.test(err.code)) {
          console.warn('Warning: Cannot access %s.', dir);
        } else {
          throw err;
        }
      } else {
        all.forEach((f) => {
          const sdir = path.join(dir, f);
          if (is.directory(sdir)) fn(sdir);
        });
        done();
      }
    });
  } else {
    done();
  }
}

/**
 * Create a semaphore for tracking async operations
 * @param {Function} final - Callback when all operations complete
 * @returns {Function} Start function
 */
function semaphore(final) {
  let counter = 0;
  return function start() {
    counter++;
    return function stop() {
      counter--;
      if (counter === 0) final();
    };
  };
}

/**
 * Null counter for single directory watching
 * @returns {Function}
 */
function nullCounter() {
  return () => {};
}

/**
 * Check if a path should be watched based on filter
 * @param {string} filePath - Path to check
 * @param {Function} filter - Filter function
 * @returns {boolean}
 */
function shouldNotSkip(filePath, filter) {
  return !is.func(filter) || filter(filePath, SKIP_FLAG) !== SKIP_FLAG;
}

/**
 * Emit ready event on watcher
 * @param {Watcher} self - Watcher instance
 */
function emitReady(self) {
  if (!self._isReady) {
    self._isReady = true;
    process.nextTick(() => self.emit('ready'));
  }
}

/**
 * Emit close event on watcher
 * @param {Watcher} self - Watcher instance
 */
function emitClose(self) {
  self.emit('close');
}

/**
 * Watcher class extending EventEmitter
 * Manages file system watchers for files and directories
 */
class Watcher extends EventEmitter {
  constructor() {
    super();
    this.watchers = {};
    this._isReady = false;
    this._isClosed = false;
    this.flag = '';
  }

  /**
   * Create an exposed interface for external use
   * @returns {Object} Exposed methods
   */
  expose() {
    const methods = [
      'on',
      'emit',
      'once',
      'close',
      'isClosed',
      'listeners',
      'setMaxListeners',
      'getMaxListeners',
      'getWatchedPaths'
    ];

    const expose = {};
    methods.forEach((name) => {
      expose[name] = (...args) => this[name](...args);
    });
    return expose;
  }

  /**
   * Check if watcher is closed
   * @returns {boolean}
   */
  isClosed() {
    return this._isClosed;
  }

  /**
   * Close watcher for a specific path or all paths
   * @param {string} [fullPath] - Specific path to close, or undefined for all
   */
  close(fullPath) {
    if (fullPath) {
      const watcher = this.watchers[fullPath];
      if (watcher?.close) {
        watcher.close();
        delete this.watchers[fullPath];
      }
      getSubDirectories(fullPath, (fpath) => this.close(fpath));
    } else {
      Object.keys(this.watchers).forEach((fpath) => {
        const watcher = this.watchers[fpath];
        if (watcher?.close) {
          watcher.close();
        }
      });
      this.watchers = {};
    }

    // Do not close the Watcher unless all child watchers are closed
    // https://github.com/yuanchuan/node-watch/issues/75
    if (is.emptyObject(this.watchers)) {
      if (!this._isClosed) {
        this._isClosed = true;
        process.nextTick(emitClose, this);
      }
    }
  }

  /**
   * Get all watched paths
   * @param {Function} fn - Callback with array of paths
   */
  getWatchedPaths(fn) {
    if (is.func(fn)) {
      if (this._isReady) {
        fn(Object.keys(this.watchers));
      } else {
        this.on('ready', () => fn(Object.keys(this.watchers)));
      }
    }
  }

  /**
   * Add a native FSWatcher to this watcher
   * @param {fs.FSWatcher} watcher - Native watcher
   * @param {Object} info - Watch info
   */
  add(watcher, info = { fpath: '' }) {
    const watcherPath = path.resolve(info.fpath);
    this.watchers[watcherPath] = watcher;

    // Debounced handler for public events
    const handlePublicEvents = debounce(info, (evt, name) => {
      // Watch single file
      if (info.compareName) {
        if (info.compareName(name)) {
          this.emit('change', evt, name);
        }
      } else {
        // Watch directory
        const filterGuard = guard(info.options.filter);
        filterGuard(name, () => {
          if (this.flag) {
            this.flag = '';
          } else {
            this.emit('change', evt, name);
          }
        });
      }
    });

    // Internal callback for handling fs.FSWatcher 'change' events
    const internalOnChange = (rawEvt, rawName) => {
      if (this.isClosed()) {
        return;
      }

      // Normalize lack of name and convert to full path
      let name = rawName ?? '';
      name = path.join(info.fpath, name);

      if (info.options.recursive) {
        hasNativeRecursive((has) => {
          if (!has) {
            const fullPath = path.resolve(name);
            // Remove watcher on removal
            if (!is.exists(name)) {
              this.close(fullPath);
            } else {
              // Watch new created directory
              const shouldWatch =
                is.directory(name) &&
                !this.watchers[fullPath] &&
                shouldNotSkip(name, info.options.filter);

              if (shouldWatch) {
                this.watchDirectory(name, info.options);
              }
            }
          }
        });
      }

      handlePublicEvents(rawEvt, name);
    };

    watcher.on('error', (err) => {
      if (this.isClosed()) {
        return;
      }
      if (is.windows() && err.code === 'EPERM') {
        watcher.emit('change', EVENT_REMOVE, info.fpath ?? '');
        this.flag = 'windows-error';
        this.close(watcherPath);
      } else {
        this.emit('error', err);
      }
    });

    watcher.on('change', internalOnChange);
  }

  /**
   * Watch a single file
   * @param {string} file - File path
   * @param {Object} options - Watch options
   * @param {Function} [fn] - Change callback
   */
  watchFile(file, options, fn) {
    const parent = path.join(file, '../');
    const opts = {
      ...options,
      filter: null, // No filter for single file
      encoding: 'utf8'
    };

    // No need to watch recursively for single file
    delete opts.recursive;

    const watcher = tryWatch(this, parent, opts);
    if (!watcher) {
      return;
    }

    this.add(watcher, {
      type: 'file',
      fpath: parent,
      options: { ...opts, encoding: options.encoding },
      compareName: (n) => is.samePath(n, file)
    });

    if (is.func(fn)) {
      this.on('change', fn);
    }
  }

  /**
   * Watch a directory
   * @param {string} dir - Directory path
   * @param {Object} options - Watch options
   * @param {Function} [fn] - Change callback
   * @param {Function} [counter] - Semaphore counter
   */
  watchDirectory(dir, options, fn, counter = nullCounter) {
    const done = counter();

    hasNativeRecursive((has) => {
      // Always specify recursive
      options.recursive = !!options.recursive;

      // Using utf8 internally
      const opts = { ...options, encoding: 'utf8' };
      if (!has) {
        delete opts.recursive;
      }

      // Check if closed before calling watch
      if (this._isClosed) {
        done();
        return this.close();
      }

      const watcher = tryWatch(this, dir, opts);
      if (!watcher) {
        done();
        return;
      }

      this.add(watcher, {
        type: 'dir',
        fpath: dir,
        options
      });

      if (is.func(fn)) {
        this.on('change', fn);
      }

      if (options.recursive && !has) {
        getSubDirectories(
          dir,
          (d) => {
            if (shouldNotSkip(d, options.filter)) {
              this.watchDirectory(d, options, null, counter);
            }
          },
          counter()
        );
      }

      done();
    });
  }
}

/**
 * Compose multiple watchers into one
 * @param {Watcher[]} watchers - Array of watchers
 * @returns {Object} Composed watcher interface
 */
function composeWatcher(watchers) {
  const watcher = new Watcher();
  const filterDups = createDupsFilter();
  let counter = watchers.length;

  watchers.forEach((w) => {
    w.on(
      'change',
      filterDups((evt, name) => watcher.emit('change', evt, name))
    );
    w.on('error', (err) => watcher.emit('error', err));
    w.on('ready', () => {
      if (!--counter) {
        emitReady(watcher);
      }
    });
  });

  watcher.close = () => {
    watchers.forEach((w) => w.close());
    process.nextTick(emitClose, watcher);
  };

  watcher.getWatchedPaths = (fn) => {
    if (is.func(fn)) {
      const promises = watchers.map(
        (w) => new Promise((resolve) => w.getWatchedPaths(resolve))
      );
      Promise.all(promises).then((result) => {
        fn(unique(result.flat(1)));
      });
    }
  };

  return watcher.expose();
}

/**
 * Watch files or directories for changes
 * @param {string|Buffer|string[]} fpath - Path(s) to watch
 * @param {Object|string|Function} [options] - Watch options or encoding string
 * @param {Function} [fn] - Change callback
 * @returns {Object} Watcher interface
 */
function watch(fpath, options, fn) {
  const watcher = new Watcher();

  // Handle Buffer input
  if (is.buffer(fpath)) {
    fpath = fpath.toString();
  }

  // Validate path exists
  if (!is.array(fpath) && !is.exists(fpath)) {
    process.nextTick(() => {
      watcher.emit('error', new Error(`${fpath} does not exist.`));
    });
  }

  // Handle encoding string as options
  if (is.string(options)) {
    options = { encoding: options };
  }

  // Handle callback as second argument
  if (is.func(options)) {
    fn = options;
    options = {};
  }

  // Default options
  if (arguments.length < 2) {
    options = {};
  }

  // Validate and set encoding
  if (options.encoding) {
    assertEncoding(options.encoding);
  } else {
    options.encoding = 'utf8';
  }

  // Handle array of paths
  if (is.array(fpath)) {
    if (fpath.length === 1) {
      return watch(fpath[0], options, fn);
    }
    const filterDups = createDupsFilter();
    return composeWatcher(
      unique(fpath).map((f) => {
        const w = watch(f, options);
        if (is.func(fn)) {
          w.on('change', filterDups(fn));
        }
        return w;
      })
    );
  }

  // Watch file
  if (is.file(fpath)) {
    watcher.watchFile(fpath, options, fn);
    emitReady(watcher);
  }
  // Watch directory
  else if (is.directory(fpath)) {
    const counter = semaphore(() => emitReady(watcher));
    watcher.watchDirectory(fpath, options, fn, counter);
  }

  return watcher.expose();
}

module.exports = watch;
module.exports.default = watch;
